spring.application.name=WorkPageSpringUTP

# Variables de entorno preparadas para Azure (con valores por defecto para tu PC local)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/techcell?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:!}

# Configuración JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
# Muestra el SQL generado en consola (puedes ponerlo en false cuando ya estés en producción)
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1